### ISSUE TITLE
error CS1061: 'VideoKitCameraManager' does not contain a definition for 'OnFrame' and no accessible extension method 'OnFrame' accepting a first argument of type 'VideoKitCameraManager' could be found (are you missing a using directive or an assembly reference?)

### ISSUE THREAD

**Issue by fatimafatimaprogrammer** [natml-hub/NanoDet#1]
Assets\NanoDetSample.cs(33,27): error CS1061: 'VideoKitCameraManager' does not contain a definition for 'OnFrame' and no accessible extension method 'OnFrame' accepting a first argument of type 'VideoKitCameraManager' could be found (are you missing a using directive or an assembly reference?)

I'm trying to run this locally but its giving this error
I'm using unity version 2021.3.21f1

**Comment by maryam-fatima** [comment]
release 0.0.6 of natml videokit refactored VideoKitCameraManager.OnFrame event to OnCameraFrame.
[Videokit releases](https://github.com/natmlx/videokit/releases)

**Comment by olokobayusuf** [comment]
[Fixed in NanoDet 1.0.1](https://github.com/natml-hub/NanoDet/releases/tag/1.0.1).
